### ISSUE TITLE
Menu sidebar disappears in rare cases

### ISSUE THREAD

**Issue by TechNovation01** [TechNovation01/nRF24Doctor#7]
The menu (right) sidebar can disappear in some cases. 
A reproducible case is as follows:

- Go into "Settings" menu
- Press Button to change "Payload value"
- Press Button to accept new "Payload value"
- Turn encoder knob in the direction upward in the menu

Now the sidebar has disappeared and re-appears when you turn the encoder knob in the downward menu direction. It appears to be related to a top menu item (which can be changed) only.

**Comment by Yveaux** [comment]
Failed to reproduce with LCDMenuLib2 v1.2.7(May 13, 2018)

**Comment by TechNovation01** [comment]
Indeed appears to be resolved, no longer reproducible with LCDMenuLib2 v1.2.7(May 13, 2018).
